GadgetBd/GadgetBd/urls.py
from django.contrib import admin
from django.urls import path, include
#library root media for url config
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include(('home.urls','app_name'), namespace = 'homeapplication')),
    path('cart/', include(('cartOrder.urls', 'app_name'), namespace='cartOrderapplication')),
]

#media file URL config(in the development stage): image show for backend to frontend

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GadgetBd/cartOrder/urls.py
from django.urls import path
from. import views

app_name='cartOrderApp'

urlpatterns = [
    #path('', views.homepage, name='homepage'),

]

GadgetBd/home/urls.py
from django.urls import path
from. import views

app_name='homeApp'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('product-detail/<str:id>', views.prodDetail, name='prodDetail'),
]

GadgetBd/cartOrder/models.py
from django.db import models
from django.contrib.auth.models import User
from home.models import Product
import random, string




#custom id generate

def random_string_generator(size=20, chars=string.ascii_lowercase + string.digits):
    return ''.join(random.choice(chars)for _ in range(size))


class Cart(models.Model):
    cart_id = models.CharField(max_length=100, blank=True)
    total_cart_items = models.PositiveIntegerField(default=0)
    total_price = models.FloatField(default=0)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta():
        verbose_name_plural = 'Cart'


    #save method
    def save(self,*args,**kwargs):
        #if no cart_id isn't passed while creating an order.
        if not len(self.cart_id):
            self.cart_id = random_string_generator()
        super(Cart,self).save(*args,**kwargs)

class CartItem(models.Model):
    cartItem_id = models.CharField(max_length=100, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cartItem_quantity = models.PositiveBigIntegerField(default=0)
    cartItem_price = models.FloatField(default=0)

    class Meta():
        verbose_name_plural = 'Cart Item'


    def save(self,*args,**kwargs):
        #if no cart_id isn't passed while creating an order.
        if not len(self.cartItem_id):
            self.cartItem_id = random_string_generator()


        self.cartItem_price = self.cartItem_quantity * self.product.prod_price
        super(CartItem, self).save(*args, **kwargs)

GadgetBd/home/models.py
from django.db import models

class Product(models.Model):
    prod_name = models.CharField(max_length=100)
    prod_desc = models.TextField()
    prod_price = models.FloatField(default=0.0)
    prod_image = models.ImageField(upload_to='prodImage', default='prodImage/default_prod_image.png', blank=True)

    class Meta():
        verbose_name_plural ='Product'

GadgetBd/cartOrder/views.py
from django.shortcuts import render

# Create your views here.

GadgetBd/home/views.py
from django.shortcuts import render
from. models import *
def homepage(request):
    prod = Product.objects.all()

 #for loop for media image show
    for p in prod:
        print('Product Image URL:', p.prod_image)

    context ={
        'prod':prod
    }



    return render(request,'home/homepage.html', context)

def prodDetail(request, id):

    prod = Product.objects.get(pk=id)
    print('Product ID:', prod.pk)
    print('Product Name:', prod.prod_name)
    print('Product Price:', prod.prod_price)
    print('Product Description:', prod.prod_desc)
    context = {
        'prod':prod
    }
    return render(request,'home/productDetail.html', context)

GadgetBd/templates/home/homepage.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title> Homepage</title>
  </head>
  <body>

  <div class="container">
      <h1> Homepage </h1>
    <div class="row bg-warning">

          {% for p in prod %}
          <div class="col-3">

            <div class="card" style="width: 18rem;margin-top:1rem;">
                  <img src="{{p.prod_image.url}}" class="card-img-top" alt="Product Image"
                     style="width:10rem;height:10rem;">
                  <div class="card-body">
                    <h3 class="card-title">{{p.prod_name}}</h3>
                    <h5 class="card-title text-danger">BDT {{p.prod_price}}</h5>
                    <p class="card-text">{{p.prod_desc | truncatechars:150}}</p>
                    <a href="{% url 'homeApp:prodDetail' p.id %}" class="btn btn-primary">View Detail {{ p.id }}</a>
                  </div>
            </div>
          </div>
          {% endfor %}
    </div>
  </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


  </body>
</html>

GadgetBd/templates/home/productDetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Product Detail </title>
</head>
<body>

    <h1> Product Detail Page </h1>
    <h1> Product Id: {{ prod.pk }} </h1>
    <h1> Product Name: {{ prod.prod_name }} </h1>
    <h1> Product Price: {{ prod.prod_price }} </h1>
    <h1> Product Description: {{ prod.prod_desc }} </h1>

    <img src="{{ prod.prod_image.url }}" alt="Product Image">




</body>
</html>